
import { Posts } from "@/components/Posts";
import { PostSearch } from "@/components/PostSearch";


// export const metadata: Metadata = {
//   title: "BitCamp программа Stage 1",
//   description: "Generated by create next app",
// };

export default function stage1() {
  
  return (
    <div className="container">
      <h1 className="">stage1</h1>
      <PostSearch />
      <ul><Posts/></ul>
    </div>
  );
}
