import type { Metadata } from "next";
import { JetBrains_Mono as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";
import { TheHeader } from "@/components/TheHeader";
import { TheFooter } from "@/components/TheFooter";
import { Providers } from "@/components/Providers";
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "BitCamp программа",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Providers>
          <TheHeader />
          <main className="pt-16">{children}</main>
          <TheFooter />
        </Providers>
      </body>
    </html>
  );
}
