// export const metadata: Metadata = {
//   title: "BitCamp программа Stage 1",
//   description: "Generated by create next app",
// };

export default function stage1({
  params: { stage },
}: {
  params: { stage: string };
}) {
  return <h1 className="">{stage}</h1>;
}
