// export const metadata: Metadata = {
//   title: "BitCamp программа Stage 1",
//   description: "Generated by create next app",
// };
import { Card, CardHeader, CardContent } from "@/components/ui/card";
import { StageKey } from "@/types/stage";

interface StageData {
  title: string;
  description: string;
  technologies: string[];
  projects: string[];
}

const stageDataMap: Record<StageKey, StageData> = {
  stage1: {
    title: "Stage_1 — Верстальщик",
    description:
      "Трехмесячный курс по верстке, который затрагивает все необходимые инструменты для успешной верстки сайтов, включая препроцессоры, сборщики и деплой своих макетов. А также обработка данных пользователя.",
    technologies: ["HTML5", "CSS", "GIT", "SCSS/SASS", "Bootstrap"],
    projects: [
      "Одностраничный лендинг",
      "Страница с формой регистрации и авторизации",
      "Лендинг с интерактивными элементами",
      "Групповой проект: Многостраничный сайт E-Commerce",
    ],
  },
  stage2: {
    title: "Stage_2 — Стажер разработчик",
    description:
      "Четырехмесячный курс по программированию на языке JavaScript, который включает в себя основы программирования и структур данных. Алгоритмическую работу с данными и их визуальное отображение в браузере. Также научимся запрашивать и отдавать данные, взаимодействовать с бекендом (сервером).",
    technologies: [
      "JavaScript",
      "Простые алгоритмы",
      "DOM",
      "BOM",
      "HTTP",
      "WebSocket",
      "REST API",
      "NodeJS",
      "ООП",
      "Работа с файлами (File Reader)",
    ],
    projects: [
      "Алгоритм подсчета цен и товаров простого интернет магазина",
      "Генератор цветовых сочетаний",
      "Адресная книга с поиском",
      "Список задач",
      "Прогноз погоды",
    ],
  },
  stage3: {
    title: "Stage_3 — Младший разработчик",
    description:
      "Трехмесячный курс по библиотеке для создания пользовательских интерфейсов React. Курс включает в себя все необходимое для успешной реализации проектов средней сложности. Рассматриваются не только основы, но и глубокое понимание принципов работы библиотеки.",
    technologies: [
      "React",
      "React router",
      "React hook form + zod",
      "Vite",
      "WebPack",
      "NPM",
      "Tailwind CSS",
      "ESLint",
      "Unit testing — Jest",
      "Axios",
    ],
    projects: [
      "Прокаченный список задач из блока JavaScript",
      "Прокаченная Адресная книга с поиском из блока JavaScript",
      "Собственный UI kit",
      "Групповой проект: Блог с авторизацией и возможностью создавать посты",
    ],
  },
  stage4: {
    title: "Stage_4 — Frontend developer",
    description:
      "Двухмесячный курс повышения квалификации, предназначенный для уверенного понимания сферы фронтенд разработки. На курсе будут рассматриваться аспекты продвинутой разработки и самые актуальные на сегодняшний день технологии.",
    technologies: [
      "TypeScript",
      "Next.js",
      "Redux",
      "Redux toolkit",
      "RTK Query",
      "React query",
      "Zustand",
      "FSD — Feature-Sliced Design",
      "SQL",
      "UI KITS + CLI generative UI kit",
    ],
    projects: [
      "SSR Blog",
      "Уникальный групповой проект, разработанный с нуля в команде",
    ],
  },
};

export default function stage1({
  params: { stage },
}: {
  params: { stage: StageKey };
}) {
  const stageData = stageDataMap[stage];
  return (
    <div className="container mx-auto p-6">
      <h1 className="text-4xl font-bold mb-4">{stageData.title}</h1>
      <p className="text-lg mb-6">{stageData.description}</p>

      <Card className="mb-6">
        <CardHeader>
          <h2 className="text-2xl font-semibold">
            Технологии, которые освоят студенты:
          </h2>
        </CardHeader>
        <CardContent>
          <ul className="list-disc list-inside">
            {stageData.technologies.map((tech: string, index: number) => (
              <li key={index}>{tech}</li>
            ))}
          </ul>
        </CardContent>
      </Card>

      {/* Практические проекты */}
      <Card className="mb-6">
        <CardHeader>
          <h2 className="text-2xl font-semibold">Практические проекты:</h2>
        </CardHeader>
        <CardContent>
          <ol className="list-decimal pl-6">
            {stageData.projects.map((project: string, index: number) => (
              <li key={index} className="mb-4">
                <h3 className="text-lg font-medium">{project}</h3>
              </li>
            ))}
          </ol>
        </CardContent>
      </Card>
    </div>
  );
}
